# Generated by Django 4.0.4 on 2022-12-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cart_doc_id_alter_cart_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='raw_response',
            field=models.JSONField(default=dict, editable=False),
        ),
        migrations.AlterField(
            model_name='cart',
            name='doc_id',
            field=models.CharField(blank=True, default='', editable=False, max_length=15),
        ),
    ]
